const AUDIT_STORE_KEY='furnicore_audit_v1';
function auditNow(){return new Date().toISOString()}
function actorName(){return (currentUser&&currentUser.email)||localStorage.getItem('furnicore_actor_name')||'Неизвестный пользователь'}
function actorShort(email){const v=String(email||actorName());return v.includes('@')?v.split('@')[0]:v}
function auditLoad(){try{return JSON.parse(localStorage.getItem(AUDIT_STORE_KEY)||'[]')}catch(e){return []}}
function auditSave(list){try{localStorage.setItem(AUDIT_STORE_KEY,JSON.stringify((list||[]).slice(0,600)))}catch(e){console.warn(e)}}
function auditAdd(type,entity,entityId,entityTitle,text,meta={}){
  const row={id:uid(),at:auditNow(),by:actorName(),type,entity,entityId:String(entityId||''),entityTitle:String(entityTitle||''),text:String(text||''),meta};
  const list=auditLoad();list.unshift(row);auditSave(list);return row;
}
function auditFor(entity,entityId){return auditLoad().filter(x=>x.entity===entity&&String(x.entityId)===String(entityId)).slice(0,60)}
function auditTime(iso){const d=new Date(iso||Date.now());return Number.isNaN(d.getTime())?'—':d.toLocaleString(currentLang==='ru'?'ru-RU':currentLang==='lv'?'lv-LV':'en-GB',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function auditUserHtml(user){const u=escapeHtml(user||'—');return `<span class="profile-chip"><span class="profile-avatar">${escapeHtml(String(user||'?').slice(0,1).toUpperCase())}</span>${u}</span>`}
function auditListHtml(entity,entityId){const rows=auditFor(entity,entityId);if(!rows.length)return '<div class="audit-empty">Истории пока нет.</div>';return `<div class="audit-list">${rows.map(r=>`<div class="audit-item"><span class="audit-dot"></span><div><b>${escapeHtml(r.text)}</b><span>${escapeHtml(auditTime(r.at))} · ${escapeHtml(r.by||'—')}</span></div></div>`).join('')}</div>`}
function metaVal(obj,key,fallback='—'){return obj&&obj[key]?obj[key]:fallback}
function ensureMeta(obj){if(!obj.meta||typeof obj.meta!=='object')obj.meta={};return obj.meta}
function hasOrderTechnology(steps){return (steps||[]).some(s=>Number(s&&s.minutes||0)>0)}
function auditListHtmlOrder(o){let rows=auditFor('order',o.id);if(!hasOrderTechnology(o.steps))rows=rows.filter(r=>r.type!=='technology');if(!rows.length)return '<div class="audit-empty">Истории пока нет.</div>';return `<div class="audit-list">${rows.map(r=>`<div class="audit-item"><span class="audit-dot"></span><div><b>${escapeHtml(r.text)}</b><span>${escapeHtml(auditTime(r.at))} · ${escapeHtml(r.by||'—')}</span></div></div>`).join('')}</div>`}
function orderProfileHtml(o){const m=ensureMeta(o);const hasTech=hasOrderTechnology(o.steps);return `<div class="audit-profile-grid"><div class="audit-card"><h5>Профиль заказа</h5><div class="audit-kv"><span>Создал заказ</span><b>${escapeHtml(metaVal(m,'createdBy'))}</b></div><div class="audit-kv"><span>Дата создания</span><b>${escapeHtml(m.createdAt?auditTime(m.createdAt):(o.date||'—'))}</b></div><div class="audit-kv"><span>Технологию сделал</span><b>${escapeHtml(hasTech?metaVal(m,'technologyBy'):'—')}</b></div><div class="audit-kv"><span>Последнее изменение</span><b>${escapeHtml(metaVal(m,'updatedBy'))}</b></div></div><div class="audit-card"><h5>История заказа</h5>${auditListHtmlOrder(o)}</div></div>`}
function materialProfileHtml(m){const a=m.attributes||{};return `<div class="audit-profile-grid"><div class="audit-card"><h5>Профиль материала</h5><div class="audit-kv"><span>Добавил материал</span><b>${escapeHtml(a.createdBy||'—')}</b></div><div class="audit-kv"><span>Дата добавления</span><b>${escapeHtml(a.createdAt?auditTime(a.createdAt):'—')}</b></div><div class="audit-kv"><span>Последнее движение</span><b>${escapeHtml(a.stockChangedBy||a.updatedBy||'—')}</b></div><div class="audit-kv"><span>Последнее изменение</span><b>${escapeHtml(a.updatedAt?auditTime(a.updatedAt):'—')}</b></div></div><div class="audit-card"><h5>История материала</h5>${auditListHtml('material',m.id)}</div></div>`}
function appendModalAudit(html){const body=document.getElementById('modalBody');if(body && !body.querySelector('.audit-profile-grid')) body.insertAdjacentHTML('beforeend',html)}
function stepsSignature(steps){return JSON.stringify((steps||[]).map(s=>({name:String(s.name||''),minutes:Number(s.minutes||0)})))}
function setOrderMetaForSave(draft,prev){const now=auditNow();const meta=Object.assign({},prev&&prev.meta?prev.meta:{});if(!prev){meta.createdBy=actorName();meta.createdAt=now;}meta.updatedBy=actorName();meta.updatedAt=now;const techChanged=!prev || stepsSignature(prev.steps)!==stepsSignature(draft.steps);if(hasOrderTechnology(draft.steps) && techChanged){meta.technologyBy=actorName();meta.technologyAt=now;}if(!hasOrderTechnology(draft.steps)){delete meta.technologyBy;delete meta.technologyAt;}draft.meta=meta;return draft;}

function safeEsc(v){return (typeof escapeHtml==='function')?escapeHtml(v):String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function rowText(row){try{return (typeof auditDisplayTextV572==='function')?auditDisplayTextV572(row):(row&&row.text)||''}catch(e){return (row&&row.text)||''}}
function cleanRow(row){if(!row)return false;if(typeof auditIsGenericMaterialUpdateV576==='function'&&auditIsGenericMaterialUpdateV576(row))return false;if(typeof auditIsGenericOrderUpdateV576==='function'&&auditIsGenericOrderUpdateV576(row))return false;const txt=String(rowText(row)||'').trim();if(!txt)return false;if(/^Материал\s+.+\s+измен[её]н$/i.test(txt))return false;if(/^Заказ\s+.+\s+измен[её]н$/i.test(txt))return false;return true}
function allRows(){const rows=(typeof auditLoad==='function'?auditLoad():[]).filter(cleanRow);return rows.sort((a,b)=>String(b.at||'').localeCompare(String(a.at||'')))}
function sectionLabel(entity){if(entity==='material')return 'Склад';if(entity==='order')return 'Заказы';if(entity==='production')return 'Производство';return 'Система'}
function entityClass(entity){if(entity==='material')return 'material';if(entity==='order')return 'order';if(entity==='production')return 'production';return 'system'}
function eventAction(row){const t=String(row.type||'');if(t.includes('create'))return 'Создание';if(t.includes('receive'))return 'Поступление';if(t.includes('write')||t.includes('stock_minus'))return 'Списание';if(t.includes('purchase')||t.includes('ordered'))return 'Закупка';if(t.includes('cancel'))return 'Отмена';if(t.includes('production'))return 'Производство';if(t.includes('order_link')||t.includes('order_qty')||t.includes('materials'))return 'Материалы заказа';if(t.includes('technology'))return 'Технология';if(t.includes('changed')||t.includes('edit'))return 'Изменение';return 'Действие'}
function auditDateShort(iso){try{return auditTime(iso)}catch(e){const d=new Date(iso||Date.now());return isNaN(d)?'—':d.toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})}}
function auditDateOnly(iso){const d=new Date(iso||Date.now());if(isNaN(d))return '';const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`}
function openFromHistory(id){const row=allRows().find(r=>String(r.id)===String(id))||(typeof auditLoad==='function'?auditLoad():[]).find(r=>String(r.id)===String(id));if(!row)return;if(row.entity==='material'&&typeof openMaterialDetail==='function')return openMaterialDetail(row.entityId);if(row.entity==='order'&&typeof openOrderView==='function')return openOrderView(row.entityId);if(row.entity==='order'&&typeof openProductionModal==='function'&&String(row.type||'').includes('production'))return openProductionModal(row.entityId)}
window.openHistoryEntityV577=openFromHistory;
function filteredHistory(){const q=String(document.getElementById('historySearchInput')?.value||'').toLowerCase().trim();const section=String(document.getElementById('historySectionFilter')?.value||'');const action=String(document.getElementById('historyActionFilter')?.value||'');const user=String(document.getElementById('historyUserFilter')?.value||'');const date=String(document.getElementById('historyDateFilter')?.value||'');return allRows().filter(r=>{const text=[rowText(r),r.entityTitle,r.by,r.type,sectionLabel(r.entity)].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(section&&String(r.entity)!==section)return false;if(action&&eventAction(r)!==action)return false;if(user&&String(r.by||'')!==user)return false;if(date&&auditDateOnly(r.at)!==date)return false;return true})}
function renderHistoryStats(){const rows=allRows();const todayStr=auditDateOnly(new Date().toISOString());const todayRows=rows.filter(r=>auditDateOnly(r.at)===todayStr).length;const mat=rows.filter(r=>r.entity==='material').length;const ord=rows.filter(r=>r.entity==='order').length;const users=new Set(rows.map(r=>r.by).filter(Boolean)).size;const box=document.getElementById('historyStats');if(!box)return;box.innerHTML=`<div class="stat"><div><span>Всего событий</span><b>${rows.length}</b></div></div><div class="stat"><div><span>Сегодня</span><b>${todayRows}</b></div></div><div class="stat"><div><span>Склад / Заказы</span><b>${mat} / ${ord}</b></div></div><div class="stat"><div><span>Пользователей</span><b>${users}</b></div></div>`}
function fillHistoryFilters(){const rows=allRows();const userSel=document.getElementById('historyUserFilter');const actionSel=document.getElementById('historyActionFilter');if(userSel){const cur=userSel.value;const users=[...new Set(rows.map(r=>r.by).filter(Boolean))].sort();userSel.innerHTML='<option value="">Все пользователи</option>'+users.map(u=>`<option value="${safeEsc(u)}">${safeEsc(u)}</option>`).join('');userSel.value=cur}if(actionSel){const cur=actionSel.value;const actions=[...new Set(rows.map(eventAction).filter(Boolean))].sort();actionSel.innerHTML='<option value="">Все действия</option>'+actions.map(a=>`<option value="${safeEsc(a)}">${safeEsc(a)}</option>`).join('');actionSel.value=cur}}
function renderSiteHistory(){const box=document.getElementById('historyTable');if(!box)return;renderHistoryStats();fillHistoryFilters();const rows=filteredHistory();if(!rows.length){box.innerHTML='<div class="history-empty"><b>Истории пока нет</b>Здесь появятся все добавления, изменения, поступления, списания, закупки и действия по заказам.</div>';return}box.innerHTML=`<div class="history-list">${rows.slice(0,300).map(r=>{const entity=sectionLabel(r.entity),cls=entityClass(r.entity),txt=rowText(r),title=r.entityTitle||r.entityId||'—';return `<div class="history-row" onclick="openHistoryEntityV577('${safeEsc(r.id)}')"><div class="history-time">${safeEsc(auditDateShort(r.at))}</div><div class="history-main"><b><span class="history-type ${cls}">${safeEsc(entity)}</span>${safeEsc(txt)}</b><span>${safeEsc(title)} · ${safeEsc(eventAction(r))}</span></div><div class="history-user">${safeEsc(r.by||'—')}</div><button class="history-go" type="button">›</button></div>`}).join('')}</div>${rows.length>300?`<div class="table-foot"><span>Показано 300 из ${rows.length}</span></div>`:''}`}
window.renderSiteHistory=renderSiteHistory;
window.clearHistoryFiltersV577=function(){['historySearchInput','historyDateFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});['historySectionFilter','historyActionFilter','historyUserFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});renderSiteHistory()};
function injectHistoryUI(){const nav=document.getElementById('mainNav');if(nav&&!nav.querySelector('[data-section="history"]')){const btn=document.createElement('button');btn.dataset.section='history';btn.innerHTML='<span class="ico"><svg viewBox="0 0 24 24"><path d="M12 8v5l3 2"/><path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 4v5h5"/></svg></span> История';const settings=[...nav.querySelectorAll('button')].find(b=>b.textContent.includes('Настройки')||b.dataset.section==='settings');nav.insertBefore(btn,settings||null)}const main=document.querySelector('.main');if(main&&!document.getElementById('history'))main.insertAdjacentHTML('beforeend',`<section id="history" class="section"><div class="topbar"><div class="title"><h2>История</h2><p>Все добавления, изменения и движения по сайту</p></div></div><div class="history-summary" id="historyStats"></div><div class="panel"><div class="history-toolbar"><div class="searchbox"><svg viewBox="0 0 24 24"><path d="M21 21l-4.3-4.3"/><circle cx="11" cy="11" r="7"/></svg><input class="input" id="historySearchInput" placeholder="Поиск по материалу, заказу, пользователю..." oninput="renderSiteHistory()"></div><select class="select" id="historySectionFilter" onchange="renderSiteHistory()"><option value="">Все разделы</option><option value="material">Склад</option><option value="order">Заказы</option><option value="production">Производство</option></select><select class="select" id="historyActionFilter" onchange="renderSiteHistory()"><option value="">Все действия</option></select><select class="select" id="historyUserFilter" onchange="renderSiteHistory()"><option value="">Все пользователи</option></select><input class="input" type="date" id="historyDateFilter" onchange="renderSiteHistory()"><button class="btn" onclick="clearHistoryFiltersV577()">Сбросить</button></div><div id="historyTable"></div></div></section>`)}
window.injectHistoryUI=injectHistoryUI;
function initHistory(){injectHistoryUI();const av=document.getElementById('appVersionBadge');if(av)av.textContent='v5.93.1 - History Core';renderSiteHistory()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initHistory);else initHistory();
